/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'chair_reminder' 
 * Target:  'chair_reminder' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32l23x.h"

/* GigaDevice::Device:GD32L23x_StdPeripherals:CMP@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_CMP
/* GigaDevice::Device:GD32L23x_StdPeripherals:CRC@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_CRC
/* GigaDevice::Device:GD32L23x_StdPeripherals:DMA@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_DMA
/* GigaDevice::Device:GD32L23x_StdPeripherals:EXTI@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_EXTI
/* GigaDevice::Device:GD32L23x_StdPeripherals:FMC@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_FMC
/* GigaDevice::Device:GD32L23x_StdPeripherals:FWDGT@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_FWDGT
/* GigaDevice::Device:GD32L23x_StdPeripherals:GPIO@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_GPIO
/* GigaDevice::Device:GD32L23x_StdPeripherals:I2C@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_I2C
/* GigaDevice::Device:GD32L23x_StdPeripherals:LPTIMER@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_LPTIMER
/* GigaDevice::Device:GD32L23x_StdPeripherals:LPUART@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_LPUART
/* GigaDevice::Device:GD32L23x_StdPeripherals:MISC@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_MISC
/* GigaDevice::Device:GD32L23x_StdPeripherals:PMU@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_PMU
/* GigaDevice::Device:GD32L23x_StdPeripherals:RCU@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_RCU
/* GigaDevice::Device:GD32L23x_StdPeripherals:RTC@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_RTC
/* GigaDevice::Device:GD32L23x_StdPeripherals:SLCD@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_SLCD
/* GigaDevice::Device:GD32L23x_StdPeripherals:SPI_I2S@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_SPI
/* GigaDevice::Device:GD32L23x_StdPeripherals:TIMER@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_TIMER
/* GigaDevice::Device:GD32L23x_StdPeripherals:USART@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_USART
/* GigaDevice::Device:GD32L23x_StdPeripherals:WWDGT@2.4.0 */
#define RTE_DEVICE_STDPERIPHERALS_WWDGT


#endif /* RTE_COMPONENTS_H */
